"""
Game Constants Package

Exports all game-related constants for easy import.
"""

from .game_constants import (
    # Game Names
    GAME_TIC_TAC_TOE_NAME,
    GAME_MEMORY_NAME,
    GAME_PUZZLE_NAME,
    GAME_QUIZ_NAME,
    GAME_FLOW_TILES_NAME,

    # Game Descriptions
    GAME_TIC_TAC_TOE_DESC,
    GAME_MEMORY_DESC,
    GAME_PUZZLE_DESC,
    GAME_QUIZ_DESC,
    GAME_FLOW_TILES_DESC,

    # Game Instructions
    GAME_TIC_TAC_TOE_INSTRUCTIONS,
    GAME_MEMORY_INSTRUCTIONS,
    GAME_PUZZLE_INSTRUCTIONS,
    GAME_QUIZ_INSTRUCTIONS,
    GAME_FLOW_TILES_INSTRUCTIONS,

    # Categories
    CATEGORY_STRATEGY,
    CATEGORY_PUZZLE,
    CATEGORY_ARCADE,
    CATEGORY_CASUAL,
    CATEGORY_EDUCATIONAL,
    CATEGORY_RELAXATION,

    # Difficulty Levels
    DIFFICULTY_EASY,
    DIFFICULTY_MEDIUM,
    DIFFICULTY_HARD,

    # Seed Data
    TIC_TAC_TOE_SEED_DATA,
    FLOW_TILES_SEED_DATA,
)

__all__ = [
    # Game Names
    'GAME_TIC_TAC_TOE_NAME',
    'GAME_MEMORY_NAME',
    'GAME_PUZZLE_NAME',
    'GAME_QUIZ_NAME',
    'GAME_FLOW_TILES_NAME',

    # Game Descriptions
    'GAME_TIC_TAC_TOE_DESC',
    'GAME_MEMORY_DESC',
    'GAME_PUZZLE_DESC',
    'GAME_QUIZ_DESC',
    'GAME_FLOW_TILES_DESC',

    # Game Instructions
    'GAME_TIC_TAC_TOE_INSTRUCTIONS',
    'GAME_MEMORY_INSTRUCTIONS',
    'GAME_PUZZLE_INSTRUCTIONS',
    'GAME_QUIZ_INSTRUCTIONS',
    'GAME_FLOW_TILES_INSTRUCTIONS',

    # Categories
    'CATEGORY_STRATEGY',
    'CATEGORY_PUZZLE',
    'CATEGORY_ARCADE',
    'CATEGORY_CASUAL',
    'CATEGORY_EDUCATIONAL',
    'CATEGORY_RELAXATION',

    # Difficulty Levels
    'DIFFICULTY_EASY',
    'DIFFICULTY_MEDIUM',
    'DIFFICULTY_HARD',

    # Seed Data
    'TIC_TAC_TOE_SEED_DATA',
    'FLOW_TILES_SEED_DATA',
]
